{% set name = "pytest-tornado" %}
{% set version = "0.8.1" %}
{% set sha256 = "b9fa1930c333b9dfe29bde90f9f42e6643278b5d0c95528a8302a7454fd3f1b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - pytest
    - tornado >=4

test:
  imports:
    - pytest_tornado

about:
  home: https://github.com/eugeniy/pytest-tornado
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: |
    A py.test plugin providing fixtures and markers to simplify testing of
    asynchronous tornado applications.

extra:
  recipe-maintainers:
    - scopatz
