travis:
  secure:
    BINSTAR_TOKEN: kdmKlTmbaYc4XAy4H8NBYaszo8/qso5gZdhPwVPcUWQDdV+lCzZVSLPh1hNxHChtZEgUVWckUxc5TvDnwBrkDuhkWLxW/Tfy2eM0luXeXlqpdtwZAOUApERPciU7R3UCiZlYeeQmrER95+1fpW8pmvC5SU3JCxP4ZjGZxhLQ3AeXuKrphcqNqDPek3ATleM0N5wjOeeHTSfQcsvDDOg8KilM0gcj45mDZbRby07F65vADJW60R0omPk2lNtNyQO0I8SsYkdE4RzjlamJMXUAQPoZBX46BCyEMup4xpyXPg3cU5ktYTA5pM+o/gG9zN/n6rYn82wjZncX0w4i5JnwnE3kCT2U2MuOA/N0ok6CJYS+vPR4xoR+cegY/Uzgp3sDIgwiLyh7IbGueYsK4gQP3AFg3279e8UC7UVX+o8HraXfTH873fde2n7QgKSXU2vVjj/jClzhPu2p/EZCijCqI061nrMBvr5KSUqiTVWRs53r/hR7hwcwZ2nCxY0WP78cXjP86VHmWTzoTFEIozCYWIkh+h7EIvar2urQ/EHytBWfoEeuyF1zgU0Ar77tvTdF5c9VmSVFo/NKdRmfMZ+ZBJyw9JZ+if0FZDGVdUEoDbkk76gPZu2pHOGwbTAKT0OtTK60VJiRIYwSCK1niUpyOh6kddb5wAWPAptHmauYzJw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
